<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('User demo')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('admin') ?>">
                        <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28"/>
                    </a>
                </div>
                <div class="collapse navbar-collapse">

                    <?= $this->navigation('admin_nav')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav')                        
                        ->setAcl($this->acl)
                        ->setRole($this->role) ?>    

                    <ul class="nav navbar-nav navbar-right">
                        <?php if($this->currentUser) : ?>                       
                            <li><a href="<?php echo $this->url('admin/verify',['action' => 'index']); ?>">
                                <span class="glyphicon glyphicon-user"></span> <?= $this->currentUser ?></a>
                            </li>
                            <li><a href="<?php echo $this->url('admin/verify',['action' => 'logout']); ?>">
                                <span class="glyphicon glyphicon-log-in"></span> Logout</a>
                            </li>
                        <?php else : ?>
                            <li><a href="<?php echo $this->url('admin/verify',['action' => 'login']); ?>">
                                <span class="glyphicon glyphicon-log-in"></span> Login</a>
                            </li> 
                        <?php endif ?>                   
                    </ul>   

                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
