<?php 
$form->setAttribute('action', $this->url('admin/role', [
    'action' => 'update',
    'id'    => $id
]));

$form->get('submit')->setValue('Update');
$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-3 col-md-6">
        <?= $this->partial('partial/messages') ?>
        <div class="panel panel-default">
        <div class="panel-heading">Edit Role</div>
        <div class="panel-body">
            <p>Please fill out the following form and click the <i>Create</i> button.</p>

                <?= $this->form()->openTag($form); ?>
                
                <div class="form-group">
                    <?= $this->formLabel($form->get('name')); ?>
                    <?= $this->formElement($form->get('name')); ?>
                    <?= $this->formElementErrors($form->get('name')); ?>                  
                </div>
                
                <div class="form-group">
                    <?= $this->formLabel($form->get('description')); ?>
                    <?= $this->formElement($form->get('description')); ?>
                    <?= $this->formElementErrors($form->get('description')); ?>                  
                </div> 
                
                <?php if (!empty($this->acl_config)) : ?>
                    <?php foreach ($this->acl_config as $value) : ?>
                        <div class="form-group">
                            <?= $this->formLabel($form->get($value['resource'])); ?>
                            <?= $this->formElement($form->get($value['resource'])) ?>
                        </div>
                    <?php endforeach ?>
                <?php endif ?>
                  
                <?= $this->formElement($form->get('submit')); ?>
                
                <?= $this->form()->closeTag(); ?>
            </div>    
        </div> 
    </div>
</div>



  