<div class="row">
	<div class="col-md-offset-2 col-md-8">
		<div class="text-right" style="margin-bottom: 10px">
			<a class="btn btn-primary btn-md" href="<?= $this->url('admin/role',['action' => 'create']); ?>">Add role</a>
		</div>		
		<div class="panel panel-default">
			<div class="panel-heading">Roles</div>
			<div class="panel-body">
				
				<?= $this->partial('partial/messages') ?>
				
				<table class="table table-striped">
					<thead>
						<tr>
							<th>STT</th>
							<th>Name</th>
							<th>Description</th>
							<th>Edit</th>
							<th>Delete</th>
						</tr>
					</thead>
					<tbody>
						<?php $stt = 1; ?>
						<?php foreach ($roles as $key => $val) : ?>
							<?php if ($val->getName() == 'admin') continue ?>
						<tr>
							<td><?= $stt ?></td>
							<td><?php echo $this->escapeHtml($val->getName()) ?></td>
							<td><?php echo $this->escapeHtml($val->getDescription()) ?></td>
							<td>
								<a href="<?= $this->url('admin/role',[
										'action' => 'edit', 
										'id' => $val->getId()
									]); ?>">
									<span class="glyphicon glyphicon-cog"></span>
								</a>
							</td>
							<td>
								<a onclick="return removeConfirm('<?= $val->getName() ?>')" href="<?= $this->url('admin/role', [
										'action' => 'delete',
										'id' => $val->getId()
									]); ?>">
									<span class="glyphicon glyphicon-remove"></span>
								</a>
							</td>
						</tr>
						<?php $stt++ ?>
						<?php endforeach ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<script>
function removeConfirm(name) {
	if (confirm("Do you want delete role " + name + '?')) {
		return true;
	} else {
		return false;
	}
}
</script>

