<?php 

$this->headTitle('Change password');

$form->setAttribute('action', $this->url('admin/verify', [
	'action' => 'active',
	'email' => $email,
	'token' => $token
]));

$form->prepare();

?>
<div class="row">
    <div class="col-md-offset-4 col-md-4">
    	<?= $this->partial('partial/messages') ?>
    	<div class="panel panel-default">
    		<div class="panel-heading">Change password</div>
    		<div class="panel-body">
			<?= $this->form()->openTag($form) ?>
				<div class="form-group">
					<?= $this->formLabel($form->get('password')) ?>
					<?= $this->formElement($form->get('password')) ?>
					<?= $this->formElementErrors($form->get('password')) ?>
				</div>

				<div class="form-group">
					<?= $this->formLabel($form->get('repassword')) ?>
					<?= $this->formElement($form->get('repassword')) ?>
					<?= $this->formElementErrors($form->get('repassword')) ?>
				</div>

	            <?= $this->formElement($form->get('csrf')) ?>

				<div class="form-group">
					<?= $this->formElement($form->get('submit')) ?>
				</div>
			<?= $this->form()->closeTag() ?>
    		</div>
    	</div>
    </div>
</div>