<?php 

$this->headTitle('Sign in');

$form->setAttribute('action', $this->url('admin/verify', [
	'action' => 'login'
]));

$form->prepare();

?>
<div class="row">
    <div class="col-md-offset-4 col-md-4">
    	<?= $this->partial('partial/messages') ?>
    	<div class="panel panel-default">
    		<div class="panel-heading">Login</div>
    		<div class="panel-body">
			<?= $this->form()->openTag($form) ?>
				<div class="form-group">
					<?= $this->formLabel($form->get('username')) ?>
					<?= $this->formElement($form->get('username')) ?>
					<?= $this->formElementErrors($form->get('username')) ?>
				</div>
				<div class="form-group">
					<?= $this->formLabel($form->get('password')) ?>
					<?= $this->formElement($form->get('password')) ?>
					<?= $this->formElementErrors($form->get('password')) ?>
				</div>
				<div class="form-group">
					<div class="row">
						<div class="col-md-6">
							<div class="text-left">
								<?= $this->formElement($form->get('remember_me')) ?>
								<span>Remember me?</span>	
							</div>
						</div>
						<div class="col-md-6">
							<div class="text-right">
								<a href="<?= $this->url('admin/verify', [
									'action' => 'forgot'
								]) ?>">Forgot password?</a>
							</div>
						</div>
					</div>
				</div>				
	            <?= $this->formElement($form->get('csrf')) ?>
				<div class="form-group">
					<?= $this->formElement($form->get('submit')) ?>
				</div>
			<?= $this->form()->closeTag() ?>
    		</div>
    	</div>
    </div>
</div>